import reflex as rx

from ..breakout_timing_state import BreakoutTimingState
from utils.constants import UNIVERSE_OPTIONS


def breakout_timing_header():
    return rx.vstack(
        rx.hstack(
            rx.vstack(
                rx.text("SOLARIS • BREAKOUT CLOCK", size="4", color="#00E5FF", font_weight="bold"),
                rx.text(
                    "Last cycle event time = daily / weekly bar timestamp (IST), same engine as Breakout.",
                    size="1",
                    color="#888888",
                ),
                align_items="start",
                spacing="0",
            ),
            rx.spacer(),
            rx.vstack(
                rx.hstack(
                    rx.link("← Breakout grid", href="/breakout", color="#FFB000", font_size="12px"),
                    spacing="3",
                ),
                rx.text("ENGINE STATUS", size="1", color="#D1D1D1", font_weight="bold"),
                rx.hstack(
                    rx.text(BreakoutTimingState.status_message, color="#FFB000", font_weight="bold", font_size="14px"),
                    rx.text(f"{BreakoutTimingState.total_count} ROWS", color="#00FF00", font_weight="bold", font_size="12px"),
                    spacing="2",
                    align_items="center",
                ),
                align_items="end",
                spacing="0",
            ),
            width="100%",
            padding="10px",
            border_bottom="1px solid #333333",
            background_color="#000000",
        ),
        spacing="0",
        width="100%",
    )


def breakout_timing_sidebar():
    profile_opts = ["ALL", "ELITE", "LEADER", "RISING", "LAGGARD", "FADING", "BASELINE"]
    timing_opts = ["ALL", "LIVE", "SUSTAINED", "SUSTAINED_W", "NOT_SUSTAINED", "E_TIMING", "E_SUSTAINED", "ANY_BRK", "D_BRK", "W_BRK"]
    brk_options = [
        "ALL",
        "LOCKED",
        "TRENDING",
        "PULLBACK",
        "B",
        "E9CT",
        "ET9DNWF21C",
        "E21C",
        "RST",
    ]
    mrs_grid_options = ["ALL", "TREND_OK"]
    wmrs_slope_options = ["ALL", "POS"]
    return rx.vstack(
        rx.text("TACTICAL / UNIVERSE", size="1", color="#D1D1D1", font_weight="bold", padding="10px 15px"),
        rx.box(
            rx.select(
                UNIVERSE_OPTIONS,
                value=BreakoutTimingState.universe,
                on_change=BreakoutTimingState.set_universe,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                height="32px",
                font_size="12px",
                margin_left="15px",
                margin_right="15px",
                _focus={"border_color": "#00E5FF"},
            ),
            width="100%",
        ),
        rx.box(height="8px"),
        rx.text("TIMING FILTER", size="1", color="#D1D1D1", font_weight="bold", padding="8px 15px 4px 15px"),
        rx.select(
            timing_opts,
            value=BreakoutTimingState.timing_filter,
            on_change=BreakoutTimingState.set_timing_filter,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.text(
            "LIVE = pending daily C* above brk. SUSTAINED = daily C*S today / live hold. "
            "SUSTAINED_W = weekly C*S today / live weekly hold. "
            "E_TIMING = E-family cycle/timing view. E_SUSTAINED = explicit CE*S tags.",
            size="1",
            color="#666666",
            padding="4px 15px 0 15px",
        ),
        rx.text("Same filters as Breakout grid", size="1", color="#888888", padding="10px 15px 4px 15px"),
        rx.text("Symbol contains", size="1", color="#888888", padding_left="15px"),
        rx.input(
            placeholder="e.g. RELIANCE",
            value=BreakoutTimingState.search_query,
            on_change=BreakoutTimingState.set_search_query,
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            border="1px solid #333333",
            bg="#111111",
            color="white",
            height="32px",
            font_size="12px",
            _focus={"border_color": "#00E5FF"},
        ),
        rx.text("PROFILE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
        rx.select(
            profile_opts,
            value=BreakoutTimingState.filter_profile,
            on_change=BreakoutTimingState.set_filter_profile,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.text(
            "ELITE/LEADER: top RS leaders | RISING: improving trend | "
            "LAGGARD: weak RS | FADING: losing momentum | BASELINE: neutral.",
            size="1",
            color="#777777",
            padding_left="15px",
            padding_right="15px",
            white_space="normal",
        ),
        rx.text("BRK STAGE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
        rx.select(
            brk_options,
            value=BreakoutTimingState.filter_brk_stage,
            on_change=BreakoutTimingState.set_filter_brk_stage,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.text("TREND FILTER", size="1", color="#888888", padding_top="8px", padding_left="15px"),
        rx.select(
            mrs_grid_options,
            value=BreakoutTimingState.filter_mrs_grid,
            on_change=BreakoutTimingState.set_filter_mrs_grid,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.text("W_MRS SLOPE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
        rx.select(
            wmrs_slope_options,
            value=BreakoutTimingState.filter_wmrs_slope,
            on_change=BreakoutTimingState.set_filter_wmrs_slope,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.text("LAST TAG PREFIX", size="1", color="#888888", padding_top="8px", padding_left="15px"),
        rx.select(
            [
                "ALL",
                "B",
                "E9CT",
                "E9CT1",
                "E9CT2",
                "E9CT3",
                "E9CT4",
                "E9CT5",
                "E9CT6",
                "E9CT7",
                "E9CT8",
                "E9CT9",
                "ET9DNWF21C",
                "E21C",
                "RST",
            ],
            value=BreakoutTimingState.filter_m_rsi2,
            on_change=BreakoutTimingState.set_filter_m_rsi2,
            color="white",
            bg="#111111",
            border="1px solid #333333",
            size="1",
            width="100%",
            max_width="260px",
            margin_left="15px",
            margin_right="15px",
            height="32px",
        ),
        rx.button(
            "EXPORT XLSX",
            on_click=BreakoutTimingState.download_excel,
            size="1",
            margin_left="15px",
            margin_right="15px",
            margin_top="10px",
            width="calc(100% - 30px)",
            bg="#00E5FF",
            color="black",
            font_weight="bold",
            _hover={"bg": "#00B8CC"},
        ),
        width="100%",
        height="100%",
        border_right="1px solid #333333",
        background_color="#000000",
        overflow_y="auto",
        flex="1",
        min_height="0",
    )
