import reflex as rx
from ..breakout_state import BreakoutState
from utils.constants import UNIVERSE_OPTIONS
def breakout_header():
    return rx.vstack(
        rx.hstack(
            rx.vstack(
                rx.text("SOLARIS • BREAKOUT STRATEGY", size="4", color="#00FF00", font_weight="bold"),
                rx.text("ISOLATED SIDECAR ENGINE", size="1", color="#D1D1D1"),
                rx.link(
                    "Open Breakout clock (daily/weekly event times →)",
                    href="/breakout-timing",
                    color="#00E5FF",
                    font_size="11px",
                    padding_top="4px",
                ),
                align_items="start", spacing="0"
            ),
            rx.spacer(),
            rx.vstack(
                rx.text("ENGINE STATUS", size="1", color="#D1D1D1", font_weight="bold"),
                rx.hstack(
                    rx.text(BreakoutState.status_message, color="#FFB000", font_weight="bold", font_size="14px"),
                    rx.text(f"{BreakoutState.result_count} SYMBOLS", color="#00FF00", font_weight="bold", font_size="12px"),
                    spacing="2", align_items="center"
                ),
                align_items="end", spacing="0"
            ),
            width="100%", padding="10px", border_bottom="1px solid #333333", background_color="#000000"
        ), spacing="0", width="100%"
    )
def breakout_sidebar():
    profile_options = ["ALL", "ELITE", "LEADER", "RISING", "LAGGARD", "FADING", "BASELINE"]
    brk_options = [
        "ALL",
        "LOCKED",
        "TRENDING",
        "PULLBACK",
        "B",
        "E9CT",
        "ET9DNWF21C",
        "E21C",
        "RST",
    ]
    mrs_grid_options = ["ALL", "TREND_OK"]
    wmrs_slope_options = ["ALL", "POS"]
    return rx.vstack(
        rx.text("TACTICAL / UNIVERSE", size="1", color="#D1D1D1", font_weight="bold", padding="10px 15px"),
        rx.box(
            rx.select(
                UNIVERSE_OPTIONS,
                value=BreakoutState.universe,
                on_change=BreakoutState.set_universe,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                height="32px",
                font_size="12px",
                margin_left="15px",
                margin_right="15px",
                _focus={"border_color": "#FFB000"},
            ),
            width="100%",
        ),
        rx.box(height="8px"),
        rx.text("FILTERS", size="1", color="#D1D1D1", font_weight="bold", padding="8px 15px 4px 15px"),
        rx.vstack(
            rx.text("Symbol contains", size="1", color="#888888", padding_left="15px"),
            rx.input(
                placeholder="e.g. RELIANCE",
                value=BreakoutState.search_query,
                on_change=BreakoutState.set_search_query,
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                border="1px solid #333333",
                bg="#111111",
                color="white",
                height="32px",
                font_size="12px",
                _focus={"border_color": "#FFB000"},
            ),
            rx.text("PROFILE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
            rx.select(
                profile_options,
                value=BreakoutState.filter_profile,
                on_change=BreakoutState.set_filter_profile,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                height="32px",
            ),
            rx.text(
                "ELITE/LEADER: top RS leaders | RISING: improving trend | "
                "LAGGARD: weak RS | FADING: losing momentum | BASELINE: neutral.",
                size="1",
                color="#777777",
                padding_left="15px",
                padding_right="15px",
                white_space="normal",
            ),
            rx.text("BRK STAGE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
            rx.select(
                brk_options,
                value=BreakoutState.filter_brk_stage,
                on_change=BreakoutState.set_filter_brk_stage,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                height="32px",
            ),
            rx.text("TREND FILTER", size="1", color="#888888", padding_top="8px", padding_left="15px"),
            rx.select(
                mrs_grid_options,
                value=BreakoutState.filter_mrs_grid,
                on_change=BreakoutState.set_filter_mrs_grid,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                height="32px",
            ),
            rx.text("W_MRS SLOPE", size="1", color="#888888", padding_top="8px", padding_left="15px"),
            rx.select(
                wmrs_slope_options,
                value=BreakoutState.filter_wmrs_slope,
                on_change=BreakoutState.set_filter_wmrs_slope,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                height="32px",
            ),
            rx.text("LAST TAG PREFIX", size="1", color="#888888", padding_top="8px", padding_left="15px"),
            rx.select(
                [
                    "ALL",
                    "B",
                    "E9CT",
                    "E9CT1",
                    "E9CT2",
                    "E9CT3",
                    "E9CT4",
                    "E9CT5",
                    "E9CT6",
                    "E9CT7",
                    "E9CT8",
                    "E9CT9",
                    "ET9DNWF21C",
                    "E21C",
                    "RST",
                ],
                value=BreakoutState.filter_m_rsi2,
                on_change=BreakoutState.set_filter_m_rsi2,
                color="white",
                bg="#111111",
                border="1px solid #333333",
                size="1",
                width="100%",
                max_width="260px",
                margin_left="15px",
                margin_right="15px",
                height="32px",
            ),
            rx.button(
                "EXPORT XLSX",
                on_click=BreakoutState.download_excel,
                size="1",
                margin_left="15px",
                margin_right="15px",
                margin_top="10px",
                width="calc(100% - 30px)",
                bg="#00FF00",
                color="black",
                font_weight="bold",
                _hover={"bg": "#00CC00"},
            ),
            spacing="1",
            width="100%",
        ),
        width="100%", height="100%", border_right="1px solid #333333", background_color="#000000"
    )
